Implement 'borrowTrusted' and 'repayBorrowBehalfTrusted' functions on a market.
cloudwalk/compound-protocol pull request #28
Opened 2022-04-07 07:37 UTC by IgorSenychCW

# Description

Added two new functions to the market contract:
- `borrowTrusted` - trusted borrower borrows assets from the protocol to their address
- `repayBorrowBehalfTrusted` - trusted repayer repays a borrow belonging to a trusted borrower

Updated market functions:
-  `borrow` - trusted borrowers disallowed to execute this function 
-  `repayBorrowBehalf` - will not be used for trusted repayments anymore

## Type of change
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)

2022-04-07 10:50 UTC, EvgeniiZaitsevCW requested changes
Only the changed code has been reviewed

2022-04-07 10:50 UTC, EvgeniiZaitsevCW commented on contracts/CTokenInterfaces.sol
> +    function borrowTrusted(uint totalAmount, uint borrowAmount, address treasury) external returns (uint);
The function has not clear name and names of its parameters.

The suggested version without changing of the function logic:
```
function borrowAndTransferTrusted(uint borrowAmount, uint nonTransferAmount, address to) external returns (uint);
```
where:
`borrowAmount` -- the amount that will be borrow from the market;
`nonTransferAmount` -- the amount that will be keep by the borrower himself from the borrowed amount, the other part will be sent to address `to`

The suggested version with changing of the function logic:
```
function borrowAndTransferTrusted(uint borrowAmount, uint transferAmount, address to) external returns (uint);
```
where:
`borrowAmount` -- the amount that will be borrow from the market;
`transferAmount` -- the amount that will be sent to address `to` from the borrowed amount, the other part will be kept by the borrower himself.

*A note:* If you agree with this remark, please do not forget to change the related code in other files too.

2022-04-07 10:50 UTC, EvgeniiZaitsevCW commented on contracts/CTokenInterfaces.sol
> +    function repayBorrowBehalfTrusted(address borrower, uint repayAmount) external returns (uint);
The name does not reveal the full functionality.
The suggested version:
```
    function mintAndRepayBorrowBehalfTrusted(address borrower, uint repayAmount) external returns (uint);
```
A note: If you agree with this remark, please do not forget to change the related code in other files too.

2022-04-07 10:50 UTC, EvgeniiZaitsevCW commented on contracts/CToken.sol
> +        uint error1 = accrueInterest();
A better name for the `error1` variable is `accrueResult`

2022-04-11 07:37 UTC, IgorSenychCW commented on contracts/CToken.sol
> +        uint error1 = accrueInterest();
Made naming changes: `error1` -> `accrueError` and `error2` -> `borrowError`.

2022-04-11 08:56 UTC, EvgeniiZaitsevCW approved these changes

2022-04-11 10:48 UTC, merged